### ISSUE TITLE
Re-Ensure brain adaptation graphs can be ran and behaviour can be outputted.

### ISSUE THREAD

**Issue by a-t-0** [a-t-0/networkx-to-lava-nc#28]
Traceback (most recent call last):
  File "/home/name/miniconda3/envs/nx2lava/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/name/miniconda3/envs/nx2lava/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/name/git/networkx-to-lava-nc/src/__main__.py", line 43, in <module>
    load_pickle_graphs()
  File "/home/name/git/networkx-to-lava-nc/src/pickle_load_graphs.py", line 73, in load_pickle_graphs
    properties_brain_adaptation_graph(
  File "/home/name/git/networkx-to-lava-nc/src/pickle_load_graphs.py", line 182, in properties_brain_adaptation_graph
    counter_neurons = print_graph_properties(brain_adaptation_graph)
  File "/home/name/git/networkx-to-lava-nc/src/pickle_load_graphs.py", line 224, in print_graph_properties
    for nodename in G.nodes:
AttributeError: 'NoneType' object has no attribute 'nodes'

**Comment by a-t-0** [comment]
Done, the radiation is only applied when the adaptation is implemented. So it was trying to get the nodes of a None object because the brain adaptation and radiation graphs did not exist for certain pickles.
