### ISSUE TITLE
Use written tests to verify the output structure in between simulation stages.

### ISSUE THREAD

**Issue by a-t-0** [a-t-0/Networkx-To-Lava-NC#86]
- [x] Apply functions that verify that the graph output structures are correct. (Re-use the code from the TTTT tests).

**Comment by a-t-0** [comment]
- [ ] Fix bug: 
```
_stages'])
Traceback (most recent call last):
  File "/home/name/miniconda3/envs/nx2lava/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/name/miniconda3/envs/nx2lava/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/name/git/Networkx-To-Lava-NC/src/__main__.py", line 26, in <module>
    Experiment_runner(
  File "/home/name/git/Networkx-To-Lava-NC/src/experiment_settings/Experiment_runner.py", line 92, in __init__
    self.run_configs = self.__perform_run(self.experiment_config)
  File "/home/name/git/Networkx-To-Lava-NC/src/experiment_settings/Experiment_runner.py", line 111, in __perform_run
    self.__perform_run_stage_4(results_nx_graphs)
  File "/home/name/git/Networkx-To-Lava-NC/src/experiment_settings/Experiment_runner.py", line 229, in __perform_run_stage_4
    export_results(results_nx_graphs)
  File "/home/name/git/Networkx-To-Lava-NC/src/process_results/process_results.py", line 87, in export_results
    verify_nx_graph_contains_correct_stages(
  File "/home/name/git/Networkx-To-Lava-NC/src/export_results/verify_nx_graphs.py", line 87, in verify_nx_graph_contains_correct_stages
    raise ValueError(
ValueError: Error, input_graph did not contain the expected stages:[1, 2, 3, 4]. Instead, it contained:[1, 2]

```
Can probably be done by:
- [ ] Replace:
```
verify_nx_graph_contains_correct_stages(
            graph_name, nx_graph, [1, 2, 3, 4]
        )
        ```
        in process_results line 87 with a test that checks whether stage 3 has been completed successfully, and adjusting the 3 in the expected_stage list accordingly. (First use "export_SNN" bool to determine if 3 should be in or not, lateron, use verification on whether the output images exist or not as indicator incombination with `export_SNN` bool.
- [ ] Then also ensure the stage 4 is added to the graphs in the `stage_4_graphs` dict.
